cask "firefox"
cask "visual-studio-code"

brew "eza"
brew "fd"
brew "fzf"
brew "htop"
brew "ripgrep"
brew "tmux"
brew "watch"

brew "dotter"
brew "gh"
brew "tldr"

brew "zsh-autopair"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "zsh-system-clipboard"
