theme = "tokyonight_storm"

[editor]
color-modes = true

[editor.file-picker]
hidden = false

[editor.lsp]
display-inlay-hints = true

[editor.smart-tab]
enable = false

[keys.normal.space]
"." = "file_picker_in_current_buffer_directory"
