theme = "gruber-darker"

[editor]
auto-info = false

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[keys.normal.space]
"i" = [":toggle lsp.display-inlay-hints"]
"." = ["file_picker_in_current_buffer_directory"]
