theme = "catppuccin_frappe"

[editor]
continue-comments = false
default-yank-register = "+"
gutters = ["diff", "line-numbers", "spacer"]

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"

[editor.lsp]
display-messages = true

[editor.soft-wrap]
enable = true

[keys.normal.space]
"i" = [":toggle lsp.display-inlay-hints"]
"." = ["file_picker_in_current_buffer_directory"]
