syntax on

set number relativenumber
set scrolloff=8 nowrap
set linebreak breakindent
set tabstop=4 softtabstop=4 shiftwidth=4
set expandtab autoindent
set hlsearch smartcase ignorecase
set undofile noswapfile
set splitright splitbelow
set clipboard=unnamedplus
set autoread

let g:netrw_banner=0

nnoremap <Esc> <cmd>nohlsearch<CR>

inoremap <C-h> <Left>
inoremap <C-j> <Down>
inoremap <C-k> <Up>
inoremap <C-l> <Right>

nnoremap gn <cmd>bnext<CR>
nnoremap gp <cmd>bprev<CR>
