syntax on

set autoindent expandtab
set number ruler scrolloff=4 mouse=a
set encoding=utf-8 fileencoding=utf-8
set ignorecase hlsearch
set clipboard=unnamed
set noswapfile
set autoread

nnoremap <silent> <C-L>   :nohlsearch<CR>
nnoremap <silent> <Tab>   :bnext<CR>
nnoremap <silent> <S-Tab> :bprev<CR>

filetype plugin indent on
