[core.files]
"ghostty/config" = "~/.config/ghostty/config"
"git/ignore" = "~/.config/git/ignore"
"vim/vimrc" = "~/.vimrc"
"zsh/zprofile" = "~/.zprofile"
"zsh/zshrc" = "~/.zshrc"

[darwin.files]
"code/settings.json" = "~/Library/Application Support/Code/User/settings.json"
"extra/hushlogin" = "~/.hushlogin"
