[core.files]
ghostty = "~/.config/ghostty"
git = "~/.config/git"
nvim = "~/.config/nvim"
tmux = "~/.config/tmux"
tmux-sessionizer = "~/.config/tms"
"zsh/zprofile" = "~/.zprofile"
"zsh/zshrc" = "~/.zshrc"

[darwin.files]
"extra/hushlogin" = "~/.hushlogin"
lazygit = "~/Library/Application Support/lazygit"

[linux.files]
lazygit = "~/.config/lazygit"
