[core.files]
fish = "~/.config/fish"
ghostty = "~/.config/ghostty"
git = "~/.config/git"
"vim/vimrc" = "~/.vimrc"

[darwin.files]
"code/settings.json" = "~/Library/Application Support/Code/User/settings.json"
"extra/hushlogin" = "~/.hushlogin"
