[core.files]
fish = "~/.config/fish"
git = "~/.config/git"
helix = "~/.config/helix"
nvim = "~/.config/nvim"
tms = "~/.config/tms"
tmux = "~/.config/tmux"
"vim/vimrc" = "~/.vimrc"

[gui.files]
ghostty = "~/.config/ghostty"
kitty = "~/.config/kitty"
zed = "~/.config/zed"

[darwin.files]
"extra/hushlogin" = "~/.hushlogin"
