[core.files]
ghostty = "~/.config/ghostty"
git = "~/.config/git"
nvim = "~/.config/nvim"
"tmux/tmux.conf" = "~/.tmux.conf"
"vim/vimrc" = "~/.vimrc"
"zsh/zprofile" = "~/.zprofile"
"zsh/zshrc" = "~/.zshrc"

[darwin.files]
"extra/hushlogin" = "~/.hushlogin"
