[core.files]
fish = "~/.config/fish"
git = "~/.config/git"
helix = "~/.config/helix"
tmux = "~/.config/tmux"

[gui.files]
ghostty = "~/.config/ghostty"

[darwin.files]
"extra/hushlogin" = "~/.hushlogin"
