[core.files]
ghostty = "~/.config/ghostty"
git = "~/.config/git"
nvim = "~/.config/nvim"
"zsh/zprofile" = "~/.zprofile"
"zsh/zshrc" = "~/.zshrc"

[darwin.files]
"extra/hushlogin" = "~/.hushlogin"
lazygit = "~/Library/Application Support/lazygit"

[linux.files]
lazygit = "~/config/lazygit"
