[core.files]
fish = "~/.config/fish"
ghostty = "~/.config/ghostty"
git = "~/.config/git"
nvim = "~/.config/nvim"
tmux = "~/.config/tmux"
"vim/vimrc" = "~/.vimrc"

[darwin.files]
"extra/hushlogin" = "~/.hushlogin"
