[term.files]
"atuin"                  = "~/.config/atuin"
"extra/hushlogin"        = "~/.hushlogin"
"git"                    = "~/.config/git"
"nvim"                   = "~/.config/nvim"
"starship/starship.toml" = "~/.config/starship.toml"
"tmux/tms.toml"          = "~/.config/tms/config.toml"
"tmux/tmux.conf"         = "~/.config/tmux/tmux.conf"
"vim/vimrc"              = "~/.vimrc"
"zsh/zprofile"           = "~/.zprofile"
"zsh/zshrc"              = "~/.zshrc"

[gui.files]
"ghostty" = "~/.config/ghostty"
"kitty"   = "~/.config/kitty"

[soy.files]
code = "~/Library/Application Support/code/User"
