export GOPATH="$HOME/.go"

if [[ -x "/opt/homebrew/bin/brew" ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

if command -v nvim > /dev/null; then
  export EDITOR=nvim
else
  export EDITOR=vim
fi

# vim: set ft=zsh
